Repository kdt-final-3/jobkok-fe, pull requests merged in 2023-04, with the labels that each got.

#61 feat: 로그인, 회원가입 페이지 유효성 검사 수정
  src/constants/signup.ts
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
Labels: Status : In Progress, Type: Enhancement

#64 feat: 인재 상세 페이지 마크업
  src/components/Layout/Layout.tsx
  src/components/Layout/Navbar.tsx
  src/components/Notification/NotiBadge.tsx
  src/index.css
  src/pages/ApplicantDetail/index.tsx
  src/pages/Notification/index.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#65 feat: 탈락 인재 보관함 마크업
  src/assets/svg/archive-tick-blue.svg
  src/assets/svg/archive-tick.svg
  src/assets/svg/test.svg
  src/assets/svg/trash.svg
  src/components/Talent/FailKeywordBadge.tsx
  src/components/Talent/FailProcedureBadge.tsx
  src/components/Talent/Spinner.tsx
  src/constants/example.ts
  src/constants/pagination.ts
  src/index.css
  src/lib/hooks/usePagination.ts
  src/lib/utils/formatDate.ts
  src/lib/utils/makeString.ts
  src/lib/utils/utils
  src/pages/TalentFail/index.tsx
  src/pages/TalentManagement/index.tsx
  src/pages/TalentManagement/swiper.css
  src/router.tsx
  src/types/talentPool.ts
  tailwind.config.cjs
Labels: Status : Reveiw Needed, Type: Enhancement

#66 feat : 기업정보변경 페이지 마크업, 디자인, 기능(버튼 토글, 유효성검사)
  src/assets/change-user-info/arrow.svg
  src/assets/change-user-info/company.svg
  src/assets/change-user-info/owner.svg
  src/assets/change-user-info/personalcard.svg
  src/assets/change-user-info/sms.svg
  src/components/ChangeUser/Box.tsx
  src/components/ChangeUser/Description.tsx
  src/components/ChangeUser/DescriptionList.tsx
  src/components/ChangeUser/Icon.tsx
  src/components/ChangeUser/InfoList.tsx
  src/components/ChangeUser/Term.tsx
  src/pages/Application/index.tsx
  src/pages/ChangeUserInfo/index.tsx
Labels: Status : In Progress, Type: Enhancement

#68 feat: 인재 현황 마크업 및 마크업 수정
  src/assets/svg/add-icon.svg
  src/assets/svg/archive-tick.svg
  src/components/Common/Banner.tsx
  src/components/Common/Button.tsx
  src/components/Common/Spinner.tsx
  src/components/Talent/TKeywordBadge.tsx
  src/index.css
  src/pages/Home/index.tsx
  src/pages/TalentFail/index.tsx
  src/pages/TalentManagement/index.tsx
  src/pages/TalentManagement/swiper.css
  src/pages/TalentStatus/index.tsx
  src/router.tsx
  tailwind.config.cjs
Labels: Status : Reveiw Needed, Type: Enhancement

#70 feat : 폼작성 페이지 마크업, 디자인
  src/assets/new-form/arrow-left.svg
  src/assets/new-form/calendar.svg
  src/assets/new-form/edit.svg
  src/components/NewForm/ContentsBox.tsx
  src/components/NewForm/RequiredBadge.tsx
  src/constants/applicant.ts
  src/pages/NewForm/index.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#71 feat: 로그인, 회원가입 페이지 마크업
  src/assets/svg/arrow-back.svg
  src/assets/svg/arrow-right.svg
  src/assets/svg/blue-logo.svg
  src/assets/svg/eye-close.svg
  src/assets/svg/eye-open.svg
  src/assets/svg/jobkok-banner.svg
  src/assets/svg/round-check.svg
  src/assets/svg/white-logo.svg
  src/assets/svg/x-icon.svg
  src/components/Signup/Complete.tsx
  src/components/Signup/Email.tsx
  src/components/Signup/Password.tsx
  src/components/Signup/Phone.tsx
  src/components/Signup/UserInfo.tsx
  src/constants/signup.ts
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/router.tsx
  tailwind.config.cjs
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#72 feat: 단체 알림 센터 테이블 보완
  src/api/notification.ts
  src/api/talentDetail.ts
  src/assets/svg/chevron-down.svg
  src/assets/svg/logo.svg
  src/assets/svg/search.svg
  src/assets/svg/send.svg
  src/components/Layout/Navbar.tsx
  src/components/Notification/BlueBadge.tsx
  src/components/Notification/NotiBadge.tsx
  src/components/Notification/Purplebadge.tsx
  src/components/Notification/RedBadge.tsx
  src/constants/applicantProcedure.ts
  src/constants/applyProcedure.ts
  src/pages/Notification/index.tsx
  src/pages/TalentDetail/index.tsx
  src/router.tsx
  src/types/notification.ts
  src/types/talentDetail.ts
Labels: Status : In Progress, Status : Reveiw Needed, Type: Enhancement

#74 feat : 지원자인증 디자인, 세부기능 수정, 지원자 관련 api 수정
  src/api/applicant.ts
  src/api/form.ts
  src/assets/applicant/logo.svg
  src/assets/svg/jobkok_banner_right.svg
  src/components/Applicant/AuthEnter.tsx
  src/components/Applicant/AuthLabel.tsx
  src/components/Applicant/AuthRow.tsx
  src/pages/ApplicantAuth/index.tsx
Labels: Status : In Progress, Category : HTML&CSS

#75 feat: 로그인 페이지 api 수정
  src/api/auth.ts
  src/api/axios.ts
  src/api/signIn.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/Navbar.tsx
  src/components/Signup/Complete.tsx
  src/components/Signup/Email.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/router.tsx
Labels: Status : In Progress, Type: Enhancement

#77 feat: 인재 상세 페이지 api 연결 및 기능 구현
  src/api/talentDetail.ts
  src/assets/svg/edit-icon.svg
  src/components/Layout/Layout.tsx
  src/components/TalentDetail/Breadcrumbs.tsx
  src/components/TalentDetail/PersonalNotiModal.tsx
  src/pages/TalentDetail/index.tsx
  src/router.tsx
  src/types/talentDetail.ts
Labels: Status : In Progress, Status : Reveiw Needed, Type: Enhancement

#83 feat : 지원서작성 디자인, 세부기능
  src/assets/applicant/arrowDown.svg
  src/assets/applicant/arrowLeft.svg
  src/assets/applicant/calendar.svg
  src/assets/applicant/complete.svg
  src/assets/applicant/incomplete.svg
  src/assets/applicant/select.svg
  src/assets/applicant/selected.svg
  src/components/Applicant/ActionBtn.tsx
  src/components/Applicant/AsideBox.tsx
  src/components/Applicant/AsideHeading.tsx
  src/components/Applicant/FieldBox.tsx
  src/components/Applicant/FieldCheckbox.tsx
  src/components/Applicant/FieldInputBox.tsx
  src/components/Applicant/FieldLabel.tsx
  src/components/Applicant/FieldLegend.tsx
  src/components/Applicant/FieldParagraph.tsx
  src/components/Applicant/FieldRow.tsx
  src/components/Applicant/GetFormInfo.tsx
  src/components/Applicant/MyKeywords.tsx
  src/components/Applicant/PolicyTerms.tsx
  src/components/Applicant/SubmitBtn.tsx
  src/components/Applicant/field/CoverLetter.tsx
  src/components/Layout/OtherLayout.tsx
  src/constants/applicant.ts
  src/pages/Application/index.tsx
  src/router.tsx
Labels: Status : In Progress, Category : HTML&CSS

#87 feat : OtherLayout 수정, 지원서 작성완료 디자인
  src/assets/png/chart.png
  src/assets/png/intro_banner_nologo_3x.png
  src/components/Layout/OtherLayout.tsx
  src/pages/ApplicantAuth/index.tsx
  src/pages/Application/index.tsx
  src/pages/Completion/index.tsx
  src/router.tsx
Labels: Status : Completed

#84 feat: 인재 상세 페이지 컴포넌트 분리, 모달 생성
  src/assets/svg/modal-confirm.svg
  src/assets/svg/modal-trash.svg
  src/components/TalentDetail/Breadcrumbs.tsx
  src/components/TalentDetail/ConfirmDocsBtn.tsx
  src/components/TalentDetail/ConfirmDocsModal.tsx
  src/components/TalentDetail/ConfirmFailBtn.tsx
  src/components/TalentDetail/ConfirmFailModal.tsx
  src/components/TalentDetail/ConfirmPassModal.tsx
  src/components/TalentDetail/EvaluationNote.tsx
  src/components/TalentDetail/Heading.tsx
  src/components/TalentDetail/InterviewInfo.tsx
  src/components/TalentDetail/PersonalNotiBtn.tsx
  src/components/TalentDetail/PersonalNotiModal.tsx
  src/components/TalentDetail/ProfileCard.tsx
  src/components/TalentDetail/Timeline.tsx
  src/pages/TalentDetail/index.tsx
Labels: Status : In Progress, Type: Enhancement

#88 feat: 탈락 인재 보관함 api 작업 진행
  src/api/talent.ts
  src/app/store.ts
  src/assets/svg/archive-tick-blue.svg
  src/components/Common/ModalForLater.tsx
  src/components/Layout/Navbar.tsx
  src/components/Talent/Pagination.tsx
  src/index.css
  src/lib/hooks/useFailedTalentQuery.ts
  src/lib/hooks/useFormList.ts
  src/lib/hooks/useLikeMutate.ts
  src/lib/hooks/usePagination.ts
  src/lib/hooks/useSearchFailedQuery.ts
  src/pages/TalentFail/index.tsx
  src/pages/TalentManagement/index.tsx
Labels: Status : Reveiw Needed, Type: Enhancement

#90 feat: 로그인 api 수정, 회원가입 페이지 세부기능 수정, 타이머 훅 생성
  public/assets/images/intro_banner_nologo_3x.png
  src/api/auth.ts
  src/api/axios.ts
  src/app/store.ts
  src/assets/svg/jobkok-banner.svg
  src/components/Layout/OtherLayout.tsx
  src/components/Signup/Email.tsx
  src/components/Signup/Password.tsx
  src/lib/hooks/useTimer.ts
  src/pages/FindUserInfo/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/router.tsx
Labels: Status : In Progress, Type: Enhancement

#91 [fix] 지원서 작성 컴포넌트 분리, index.css apply 예약어 추가,
  src/api/applicant.ts
  src/api/axios.ts
  src/components/Applicant/ActionBtn.tsx
  src/components/Applicant/AsideBox.tsx
  src/components/Applicant/AsideHeading.tsx
  src/components/Applicant/FieldBox.tsx
  src/components/Applicant/FieldCheckbox.tsx
  src/components/Applicant/FieldInputBox.tsx
  src/components/Applicant/FieldLabel.tsx
  src/components/Applicant/FieldLegend.tsx
  src/components/Applicant/FieldParagraph.tsx
  src/components/Applicant/FieldRow.tsx
  src/components/Applicant/MyKeywords.tsx
  src/components/Applicant/SubmitBtn.tsx
  src/components/Applicant/field/CoverLetter.tsx
  src/components/Applicant/field/FieldAwards.tsx
  src/components/Applicant/field/FieldCareer.tsx
  src/components/Applicant/field/FieldCertificate.tsx
  src/components/Applicant/field/FieldCoverLetter.tsx
  src/components/Applicant/field/FieldEdu.tsx
  src/components/Applicant/field/FieldKeywords.tsx
  src/components/Applicant/field/FieldLanguage.tsx
  src/components/Applicant/field/FieldLink.tsx
  src/components/Applicant/field/FieldPreference.tsx
  src/components/Applicant/field/FieldTermAgree.tsx
  src/index.css
  src/pages/ApplicantAuth/index.tsx
  src/pages/Application/index.tsx
  src/types/application.ts
Labels: Status : In Progress

#92 feat: 회원가입 api 작업
  src/api/auth.ts
  src/api/form.ts
  src/components/Layout/Navbar.tsx
  src/components/Signup/Complete.tsx
  src/components/Signup/Email.tsx
  src/components/Signup/Password.tsx
  src/components/Signup/Phone.tsx
  src/components/Signup/UserInfo.tsx
  src/constants/signup.ts
  src/features/signUpSlice.ts
  src/pages/SignIn/index.tsx
Labels: Status : In Progress, Type: Enhancement

#93 feat: 알림 센터 검색 기능 구현
  src/api/notification.ts
  src/api/talent.ts
  src/assets/svg/newlogo.svg
  src/components/Layout/Navbar.tsx
  src/constants/applyProcedure.ts
  src/lib/hooks/useGetTalentQuery.ts
  src/lib/hooks/useSearchTalent.ts
  src/lib/hooks/useSelectForm.ts
  src/pages/Notification/index.tsx
  src/router.tsx
  src/types/notification.ts
Labels: Status : In Progress, Type: Enhancement

#95 feat : 채용폼 작성 세부기능, 탭 컴포넌트 추가
  src/api/form.ts
  src/assets/applicant/calendar.svg
  src/assets/applicant/logo.svg
  src/assets/new-form/calendar.svg
  src/assets/new-form/edit.svg
  src/assets/svg/check-blue.svg
  src/assets/svg/check-gray.svg
  src/assets/svg/check-round-full-blue.svg
  src/assets/svg/check-round-line-gray.svg
  src/assets/svg/chevron-down-gray.svg
  src/assets/svg/chevron-down-lightgray.svg
  src/assets/svg/chevron-left-white.svg
  src/assets/svg/chevron-left.svg
  src/assets/svg/company.svg
  src/assets/svg/owner.svg
  src/assets/svg/personalcard.svg
  src/assets/svg/sms.svg
  src/components/Applicant/FieldCheckbox.tsx
  src/components/Applicant/FieldInputBox.tsx
  src/components/Applicant/field/FieldAwards.tsx
  src/components/Applicant/field/FieldCareer.tsx
  src/components/Applicant/field/FieldCertificate.tsx
  src/components/Applicant/field/FieldCoverLetter.tsx
  src/components/Applicant/field/FieldEdu.tsx
  src/components/Applicant/field/FieldKeywords.tsx
  src/components/Applicant/field/FieldLanguage.tsx
  src/components/Applicant/field/FieldLink.tsx
  src/components/Applicant/field/FieldPreference.tsx
  src/components/NewForm/ContentsBox.tsx
  src/components/NewForm/EditTypeBadge.tsx
  src/components/NewForm/FormBox.tsx
  src/components/NewForm/FormInputBox.tsx
  src/components/NewForm/FormSelectBox.tsx
  src/components/NewForm/ProcessBadge.tsx
  src/components/NewForm/SaveModal.tsx
  src/index.css
  src/lib/utils/convertIsoDate.ts
  src/lib/utils/copyClipboard.tsx
  src/pages/ApplicantAuth/index.tsx
  src/pages/Application/index.tsx
  src/pages/ChangeUserInfo/index.tsx
  src/pages/NewForm/index.tsx
  src/types/application.ts
  src/types/form.ts
Labels: Status : In Progress

#96 feat: 인재 관리, 탈락, 현황 api 작업
  index.html
  public/assets/svg/thumbs-7.svg
  public/assets/svg/thumbs-8.svg
  public/assets/svg/thumbs-9.svg
  src/api/talent.ts
  src/components/Layout/Layout.tsx
  src/components/Talent/NumberBadge.tsx
  src/components/Talent/Pagination.tsx
  src/components/Talent/ProcedureBadge.tsx
  src/components/Talent/Slider.tsx
  src/constants/badgeStyle.ts
  src/features/examSlice.ts
  src/lib/hooks/useAllTalentQuery.ts
  src/lib/hooks/useDnD.ts
  src/lib/hooks/useFailedTalentQuery.ts
  src/lib/hooks/useFormList.ts
  src/lib/hooks/useFormListQuery.ts
  src/lib/hooks/useFormStatusQuery.ts
  src/lib/hooks/usePagination.ts
  src/lib/hooks/useSearchFailedQuery.ts
  src/lib/hooks/useTalentByProcedureQuery.ts
  src/lib/utils/ceilPage.ts
  src/lib/utils/sortWithSlice.ts
  src/lib/utils/talentByProcedure.ts
  src/main.tsx
  src/pages/Notification/index.tsx
  src/pages/TalentFail/index.tsx
  src/pages/TalentManagement/index.tsx
  src/pages/TalentStatus/index.tsx
  src/router.tsx
  src/types/talent.ts
Labels: Status : Reveiw Needed, Type: Enhancement

#97 chore: 빌드 오류 수정을 위한 PR
  src/api/notification.ts
  src/lib/hooks/useSearchTalent.ts
  src/pages/Notification/index.tsx
Labels: Status : In Progress, Type: Enhancement

#98 feat: 폼링크관리 페이지 마크업 작업
  src/api/auth.ts
  src/assets/svg/blue-logo.svg
  src/assets/svg/chevron-down-large.svg
  src/assets/svg/chevron-right-large.svg
  src/assets/svg/copy.svg
  src/assets/svg/trash-gray.svg
  src/assets/svg/white-logo.svg
  src/components/LinkForm/FormList.tsx
  src/components/LinkForm/FormSlider.tsx
  src/components/Signup/Email.tsx
  src/constants/signup.ts
  src/lib/hooks/useTimer.ts
  src/pages/LinkForm/index.tsx
Labels: Status : In Progress, Type: Enhancement

#99 feat: 로그인 정보 리덕스를 활용한 클라이언트 상태 관리
  src/api/auth.ts
  src/app/store.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/Navbar.tsx
  src/components/Layout/OtherLayout.tsx
  src/features/authSlice.ts
  src/pages/SignIn/index.tsx
  src/router.tsx
Labels: Status : Reveiw Needed, Type: Enhancement

#100 feat: 알림 센터 기능 구현
  src/pages/Notification/index.tsx
  src/types/notification.ts
Labels: Status : In Progress, Type: Enhancement

#101 feat: 미인증 에러(`400`) 해결을 위한 axios interceptors 구현
  src/api/auth.ts
  src/api/axios.ts
Labels: Status : Reveiw Needed, Type: Enhancement

#102 fix: axios.ts 오류 수정
  src/api/axios.ts
Labels: Type: Bug, Status : Reveiw Needed

#103 feat: 회원가입, 비밀번호 찾기 페이지 api작업
  package-lock.json
  package.json
  src/api/auth.ts
  src/components/FindUserInfo/AuthCode.tsx
  src/components/FindUserInfo/AuthEmail.tsx
  src/components/FindUserInfo/EditPassword.tsx
  src/components/Layout/Navbar.tsx
  src/components/Signup/Email.tsx
  src/components/Signup/Password.tsx
  src/lib/hooks/useTimer.ts
  src/pages/FindUserInfo/index.tsx
  src/pages/LinkForm/index.tsx
  src/pages/LinkForm/swiper.css
Labels: Status : In Progress, Type: Enhancement

#107 feat: 인재관련 페이지 기능 구현
  .gitignore
  src/api/axios.ts
  src/api/talent.ts
  src/assets/svg/archive-tick-blue.svg
  src/components/Talent/Pagination.tsx
  src/components/Talent/Slider.tsx
  src/components/Talent/SliderWrapper.tsx
  src/lib/hooks/useLikeMutate.ts
  src/lib/hooks/usePagination.ts
  src/pages/TalentFail/index.tsx
  src/pages/TalentManagement/index.tsx
  src/pages/TalentManagement/swiper.css
  src/pages/TalentStatus/index.tsx
  src/types/talent.ts
Labels: Status : Reveiw Needed, Type: Enhancement

#108 feat: 단체 알림 보내기 기능 구현
  src/api/notification.ts
  src/api/talentDetail.ts
  src/components/Notification/SendingBox.tsx
  src/components/Notification/TalentSearchBar.tsx
  src/components/TalentDetail/ConfirmDocsBtn.tsx
  src/components/TalentDetail/ConfirmDocsModal.tsx
  src/components/TalentDetail/EvaluationNote.tsx
  src/components/TalentDetail/InterviewInfo.tsx
  src/components/TalentDetail/ProfileCard.tsx
  src/lib/hooks/useConfirmDocsMutate.ts
  src/lib/hooks/useGetTalentQuery.ts
  src/lib/hooks/useSearchTalent.ts
  src/pages/Notification/index.tsx
  src/pages/TalentDetail/index.tsx
  src/types/notification.ts
  src/types/talentDetail.ts
Labels: Status : In Progress, Type: Enhancement

#110 feat: 인재 관련 페이지 작업 진행 중
  src/api/talent.ts
  src/components/Talent/Pagination.tsx
  src/lib/hooks/useAllTalentQuery.ts
  src/lib/hooks/useFailedTalentQuery.ts
  src/pages/TalentFail/index.tsx
  src/pages/TalentStatus/index.tsx
Labels: Status : In Progress, Status : Reveiw Needed, Type: Enhancement

#111 feat : 채용폼 작성, 지원서 작성 수정
  src/assets/svg/check-gray-100.svg
  src/components/Applicant/field/FieldAwards.tsx
  src/components/Applicant/field/FieldCareer.tsx
  src/components/Applicant/field/FieldCertificate.tsx
  src/components/Applicant/field/FieldCoverLetter.tsx
  src/components/Applicant/field/FieldEdu.tsx
  src/components/Applicant/field/FieldKeywords.tsx
  src/components/Applicant/field/FieldLanguage.tsx
  src/components/Applicant/field/FieldLink.tsx
  src/components/Applicant/field/FieldPreference.tsx
  src/components/NewForm/FormBox.tsx
  src/components/NewForm/FormInputBox.tsx
  src/components/NewForm/FormModal.tsx
  src/components/NewForm/FormSelectBox.tsx
  src/components/NewForm/SaveModal.tsx
  src/constants/applicant.ts
  src/pages/Application/index.tsx
  src/pages/NewForm/index.tsx
Labels: Status : Completed

#113 feat: 타임라인, 면접 일정 조율, 개별 알림 보내기 기능
  src/api/talentDetail.ts
  src/components/Layout/Navbar.tsx
  src/components/TalentDetail/ConfirmInterviewModal.tsx
  src/components/TalentDetail/ConfirmPassModal.tsx
  src/components/TalentDetail/InterviewInfo.tsx
  src/components/TalentDetail/PersonalNotiBtn.tsx
  src/components/TalentDetail/PersonalNotiModal.tsx
  src/components/TalentDetail/ProfileCard.tsx
  src/components/TalentDetail/Timeline.tsx
  src/lib/hooks/useApplyPassMutate.tsx
  src/lib/hooks/useSetInterviewMutate.ts
  src/lib/utils/formatTime.ts
  src/pages/TalentDetail/index.tsx
Labels: Status : Reveiw Needed, Type: Enhancement

#114 feat : 기업정보변경 디자인
  src/assets/svg/profile-heart.svg
  src/pages/ChangeUserInfo/index.tsx
Labels: Status : Completed

#115 feat: 검색결과, 폼관리 메인페이지 작업
  src/api/form.ts
  src/assets/svg/link.svg
  src/components/FindUserInfo/AuthCode.tsx
  src/components/LinkForm/FormList.tsx
  src/components/LinkForm/FormSlider.tsx
  src/components/Signup/Email.tsx
  src/lib/utils/formatDateTime.ts
  src/pages/LinkForm/index.tsx
  src/pages/LinkForm/otherFormList.json
  src/pages/SignIn/index.tsx
Labels: Status : In Progress, Type: Enhancement

#117 feat: 인재 정보가 없을 경우 처리
  src/api/talentDetail.ts
  src/pages/TalentDetail/index.tsx
  src/types/talentDetail.ts
Labels: Status : In Progress, Type: Enhancement

#118 chore: `main` 브랜치 배포를 위한 `develop` 브랜치 머지용 PR
  src/api/form.ts
  src/api/talent.ts
  src/api/talentDetail.ts
  src/assets/svg/check-gray-100.svg
  src/assets/svg/link.svg
  src/assets/svg/profile-heart.svg
  src/components/Applicant/field/FieldAwards.tsx
  src/components/Applicant/field/FieldCareer.tsx
  src/components/Applicant/field/FieldCertificate.tsx
  src/components/Applicant/field/FieldCoverLetter.tsx
  src/components/Applicant/field/FieldEdu.tsx
  src/components/Applicant/field/FieldKeywords.tsx
  src/components/Applicant/field/FieldLanguage.tsx
  src/components/Applicant/field/FieldLink.tsx
  src/components/Applicant/field/FieldPreference.tsx
  src/components/FindUserInfo/AuthCode.tsx
  src/components/Layout/Navbar.tsx
  src/components/LinkForm/FormList.tsx
  src/components/LinkForm/FormSlider.tsx
  src/components/NewForm/FormBox.tsx
  src/components/NewForm/FormInputBox.tsx
  src/components/NewForm/FormModal.tsx
  src/components/NewForm/FormSelectBox.tsx
  src/components/NewForm/SaveModal.tsx
  src/components/Signup/Email.tsx
  src/components/Talent/Pagination.tsx
  src/components/TalentDetail/ConfirmInterviewModal.tsx
  src/components/TalentDetail/ConfirmPassModal.tsx
  src/components/TalentDetail/InterviewInfo.tsx
  src/components/TalentDetail/PersonalNotiBtn.tsx
  src/components/TalentDetail/PersonalNotiModal.tsx
  src/components/TalentDetail/ProfileCard.tsx
  src/components/TalentDetail/Timeline.tsx
  src/constants/applicant.ts
  src/lib/hooks/useAllTalentQuery.ts
  src/lib/hooks/useApplyPassMutate.tsx
  src/lib/hooks/useFailedTalentQuery.ts
  src/lib/hooks/useSetInterviewMutate.ts
  src/lib/utils/formatDateTime.ts
  src/lib/utils/formatTime.ts
  src/pages/Application/index.tsx
  src/pages/ChangeUserInfo/index.tsx
  src/pages/LinkForm/index.tsx
  src/pages/LinkForm/otherFormList.json
  src/pages/NewForm/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/TalentDetail/index.tsx
  src/pages/TalentFail/index.tsx
  src/pages/TalentStatus/index.tsx
  src/types/talentDetail.ts
Labels: Type: Enhancement

#119 fix: 로그인 오류 수정
  src/pages/SignIn/index.tsx
Labels: Status : Completed

#120 chore: 콘솔로그 삭제
  src/pages/TalentFail/index.tsx
  src/pages/TalentStatus/index.tsx
Labels: Type: Enhancement, Type: Maintenance

#121 refactor: 인재 관련 페이지 리팩토링 진행
  src/components/Talent/Kanban.tsx
  src/components/Talent/KanbanBoard.tsx
  src/components/Talent/KanbanHeader.tsx
  src/lib/hooks/useAllTalentQuery.ts
  src/lib/hooks/useDnD.ts
  src/lib/utils/talentByProcedure.ts
  src/pages/NotFound/index.tsx
  src/pages/TalentManagement/index.tsx
  src/pages/TalentStatus/index.tsx
  src/types/talent.ts
Labels: Status : In Progress, Status : Reveiw Needed, Type: Enhancement

#122 feat: 인재 상세페이지 하단 탭 구현
  package-lock.json
  package.json
  src/api/notification.ts
  src/api/talentDetail.ts
  src/components/NewForm/TalentResume.tsx
  src/components/TalentDetail/ConfirmDocsBtn.tsx
  src/components/TalentDetail/ConfirmFailModal.tsx
  src/components/TalentDetail/ConfirmInterviewModal.tsx
  src/components/TalentDetail/ConfirmPassModal.tsx
  src/components/TalentDetail/EvaluationNote.tsx
  src/components/TalentDetail/ProfileCard.tsx
  src/components/TalentDetail/TalentAwards.tsx
  src/components/TalentDetail/TalentCarrer.tsx
  src/components/TalentDetail/TalentCertificate.tsx
  src/components/TalentDetail/TalentEdu.tsx
  src/components/TalentDetail/TalentEtc.tsx
  src/components/TalentDetail/TalentLanguage.tsx
  src/components/TalentDetail/TalentPreference.tsx
  src/lib/hooks/useConfirmDocsMutate.ts
  src/lib/hooks/useEvaluationMutate.ts
  src/pages/Notification/index.tsx
  src/pages/TalentDetail/index.tsx
Labels: Status : In Progress, Status : Reveiw Needed, Type: Enhancement

#123 chore: `main` 브랜치 배포를 위한 `develop` 브랜치 머지용 PR
  package-lock.json
  package.json
  src/api/notification.ts
  src/api/talentDetail.ts
  src/components/NewForm/TalentResume.tsx
  src/components/Talent/Kanban.tsx
  src/components/Talent/KanbanBoard.tsx
  src/components/Talent/KanbanHeader.tsx
  src/components/TalentDetail/ConfirmDocsBtn.tsx
  src/components/TalentDetail/ConfirmFailModal.tsx
  src/components/TalentDetail/ConfirmInterviewModal.tsx
  src/components/TalentDetail/ConfirmPassModal.tsx
  src/components/TalentDetail/EvaluationNote.tsx
  src/components/TalentDetail/ProfileCard.tsx
  src/components/TalentDetail/TalentAwards.tsx
  src/components/TalentDetail/TalentCarrer.tsx
  src/components/TalentDetail/TalentCertificate.tsx
  src/components/TalentDetail/TalentEdu.tsx
  src/components/TalentDetail/TalentEtc.tsx
  src/components/TalentDetail/TalentLanguage.tsx
  src/components/TalentDetail/TalentPreference.tsx
  src/lib/hooks/useAllTalentQuery.ts
  src/lib/hooks/useConfirmDocsMutate.ts
  src/lib/hooks/useDnD.ts
  src/lib/hooks/useEvaluationMutate.ts
  src/lib/utils/talentByProcedure.ts
  src/pages/NotFound/index.tsx
  src/pages/Notification/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/TalentDetail/index.tsx
  src/pages/TalentFail/index.tsx
  src/pages/TalentManagement/index.tsx
  src/pages/TalentStatus/index.tsx
  src/types/talent.ts
Labels: Type: Enhancement

#124 chore: 주석 제거
  src/router.tsx
Labels: Type: Enhancement

#125 chore: 불필요한 console.log 삭제
  src/components/Notification/SendingBox.tsx
  src/components/TalentDetail/PersonalNotiModal.tsx
  src/lib/hooks/useGetTalentQuery.ts
  src/lib/hooks/useSearchTalent.ts
Labels: Status : Reveiw Needed, Type: Enhancement

#126 chore: `main` 브랜치 배포를 위한 `develop` 브랜치 머지용 PR
  src/components/Notification/SendingBox.tsx
  src/components/TalentDetail/PersonalNotiModal.tsx
  src/lib/hooks/useGetTalentQuery.ts
  src/lib/hooks/useSearchTalent.ts
Labels: Type: Enhancement

#128 refactor: axios 인터셉터 수정
  src/api/axios.ts
  src/router.tsx
Labels: Type: Enhancement
