Repository kdt-final-3/jobkok-fe, pull requests merged in 2023-03, with the labels that each got.

#11 chore: `netlify` 배포용 파일 추가
  public/_redirects
  src/pages/Test/index.tsx
  src/router.tsx
Labels: Status : In Progress, Type: Enhancement

#13 chore: 배포용 명령어 수정 및 테스트 컴포넌트 추가
  package.json
  public/_redirects
  src/pages/Test/index.tsx
  src/router.tsx
Labels: Status : In Progress, Type: Bug, Type: Enhancement

#17 env: `svg` 사용을 위한 플러그인 설치
  package-lock.json
  package.json
  src/pages/Home/index.tsx
  src/svg/test.svg
  vite.config.ts
Labels: Status : In Progress, Type: Enhancement

#26 feat: aside 생성
  src/App.tsx
  src/components/Aside.tsx
  src/pages/Home/index.tsx
Labels: Status : Completed, Type: Enhancement

#27 feat: 라우터 추가
  package.json
  src/App.tsx
  src/components/Layout/Aside.tsx
  src/components/Layout/Layout.tsx
  src/index.css
  src/pages/ApplicantAuth/index.tsx
  src/pages/ApplicantDetail/index.tsx
  src/pages/Application/index.tsx
  src/pages/ChangeUserInfo/index.tsx
  src/pages/ClosedForm/index.tsx
  src/pages/Completion/index.tsx
  src/pages/ConfirmPassword/index.tsx
  src/pages/EditForm/index.tsx
  src/pages/FindUserInfo/index.tsx
  src/pages/Home/index.tsx
  src/pages/LinkForm/index.tsx
  src/pages/NewForm/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Notification/index.tsx
  src/pages/SearchForm/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/TalentFail/index.tsx
  src/pages/TalentStatus/index.tsx
  src/pages/Test/index.tsx
  src/router.tsx
Labels: Status : In Progress, Type: Enhancement

#29 chore: husky 오류 해결
  .husky/pre-commit
  package-lock.json
  package.json
  src/pages/TalentManagement/index.tsx
  src/router.tsx
Labels: Type: Bug, Status : Completed

#34 feat: 인재관리 HTML 구조 잡기
  index.html
  src/pages/TalentManagement/index.tsx
Labels: Status : Completed, Type: Enhancement

#35 feat: 인재풀 관련 api 함수 모듈화 및 타입 지정
  src/api/axios.ts
  src/api/talentPool.ts
  src/constants/example.ts
  src/pages/TalentManagement/index.tsx
  src/types/example.ts
  src/types/talentPool.ts
Labels: Status : Accepted, Type: Enhancement

#36 feat: 인재 상세 페이지 마크업
  src/components/Layout/Layout.tsx
  src/pages/ApplicantDetail/index.tsx
Labels: Status : Completed, Type: Enhancement, Category : HTML&CSS

#41 feat: 로그인 페이지 구조 및 유효성 검사
  package-lock.json
  package.json
  src/pages/SignIn/index.tsx
Labels: Status : In Progress, Type: Enhancement

#45 feat: navbar 마크업 진행
  package-lock.json
  package.json
  src/components/Layout/Aside.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/Navbar.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#46 feat: 인재 관리 페이지 마크업
  package-lock.json
  package.json
  src/assets/svg/test.svg
  src/components/Layout/Navbar.tsx
  src/pages/TalentManagement/index.css
  src/pages/TalentManagement/index.tsx
  src/router.tsx
  tailwind.config.cjs
Labels: Status : Reveiw Needed, Type: Enhancement

#48 feat : 지원자 인증 페이지 기능 구현, 지원서 작성 및 완료 페이지 마크업
  src/api/applicant.ts
  src/components/Applicant/getFormInfo.tsx
  src/components/Applicant/policyTerms.tsx
  src/constants/applicant.ts
  src/pages/ApplicantAuth/index.tsx
  src/pages/Application/index.tsx
  src/pages/Completion/index.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#49 feat: 알림 센터 마크업 진행
  src/pages/Notification/index.tsx
Labels: Status : Reveiw Needed, Type: Enhancement, Category : HTML&CSS

#50 feat: 인재 관리 페이지 작업
  src/components/Talent/Heading.tsx
  src/lib/hooks/hooks
  src/lib/hooks/useDnD.ts
  src/pages/TalentManagement/index.css
  src/pages/TalentManagement/index.tsx
Labels: Status : Reveiw Needed, Type: Enhancement

#58 feat: 인재 관리 페이지 마크업
  public/assets/svg/thumbs-1.svg
  public/assets/svg/thumbs-2.svg
  public/assets/svg/thumbs-3.svg
  public/assets/svg/thumbs-4.svg
  public/assets/svg/thumbs-5.svg
  public/assets/svg/thumbs-6.svg
  src/assets/svg/archive-tick.svg
  src/assets/svg/calendar.svg
  src/assets/svg/chevron-right.svg
  src/assets/svg/heart-memoji.svg
  src/assets/svg/pin.svg
  src/assets/svg/rocket.svg
  src/assets/svg/smile.svg
  src/assets/svg/stats.svg
  src/components/Talent/NumberBadge.tsx
  src/components/Talent/ProcedureBadge.tsx
  src/pages/TalentManagement/index.css
  src/pages/TalentManagement/index.tsx
  src/pages/TalentManagement/swiper.css
Labels: Status : Reveiw Needed, Type: Enhancement, Category : HTML&CSS

#55 feat: 회원가입 페이지 마크업 및 유효성 검사
  src/api/signIn.ts
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#56 feat : 지원자인증 zod 적용, 지원서작성 유효성 검사
  src/components/Applicant/GetFormInfo.tsx
  src/components/Applicant/PolicyTerms.tsx
  src/constants/applicant.ts
  src/pages/ApplicantAuth/index.tsx
  src/pages/Application/index.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS

#59 feat: 인재 관리 페이지 마크업 완료
  src/assets/svg/smile.svg
  src/components/Talent/InterviewBadge.tsx
  src/components/Talent/KeywordBadge.tsx
  src/components/Talent/PreferentialBadge.tsx
  src/pages/TalentManagement/index.tsx
Labels: Status : Reveiw Needed, Type: Enhancement, Category : HTML&CSS

#60 feat: 인재 상세 페이지 마크업
  src/assets/svg/backspace.svg
  src/assets/svg/nav-profile.svg
  src/assets/svg/profile-detail.svg
  src/components/Layout/Layout.tsx
  src/components/Layout/Navbar.tsx
  src/index.css
  src/pages/ApplicantDetail/index.tsx
  src/router.tsx
Labels: Status : In Progress, Type: Enhancement, Category : HTML&CSS
